apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lms.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "lms.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.db | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  DATABASE_URL: "mysql+pymysql://{{ .Values.mariadb.user }}:{{ .Values.mariadb.password }}@{{ include "lms.fullname" . }}-mariadb:{{ .Values.mariadb.service.port }}/{{ .Values.mariadb.db }}"
  REDIS_URL: "redis://{{ include "lms.fullname" . }}-redis:{{ .Values.redis.service.port }}"
