{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms.fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ include "lms.fullname" . }}-redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
{{- end }}
